# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 411eec88d38e175da2c0da9edcd809f7db717b675278c94e861fc8da16e083790672c01ae265ab59a1019631f97cca6c662731d0b0400c5497b30293a203f954

test:
  secret_key_base: c0f2813f3a3b8d760c59af5edcec46c68a1fdce3204a7db50210f76dfe02ced08f0daec943267b4133fd8d7b796d843d8e1b78a3ee5dc78ceed38794b2af451e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
